<a href="https://colab.research.google.com/github/xenacode-art/BlogPost/blob/master/numpy%20arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#A simple python code
# A code to change your name to an assigned new one
def change_name(name):
  print('the passed name is' + name)
  # changing name
  name = "Harry potter"
  print("the new name in this function is " + name )
  return
# calling the functin
name =  "John"
change_name = (name) 

In [7]:
# Machine learning with python
import numpy as np
# x = np.array([1,2,3,4,5])
# y = np.array([9,10])
# print (x)
# print('the shape of X is', x.shape) 

# print(y)
# print('the shape of Y is', y.shape)
z = np.array([[1,2], [3,4]])
print(z)
print('the shape of z is ', z.shape)

[[1 2]
 [3 4]]
the shape of z is  (2, 2)


In [8]:
w = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24],[25,26,27]]])
print(w,'\n')
print(w.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]
  [25 26 27]]] 

(1, 9, 3)
